# This is my sample .ipynb file!
This could be your analyses files, your visualization files, etc.

In [1]:
print('Hello FIN 377 class!')

Hello FIN 377 class!

In [5]:
import pandas as pd
import numpy as np

# Create some fake data
dates = pd.date_range('20220101', periods=7)
symbols = ['AAPL', 'GOOG', 'AMZN', 'FB', 'NFLX', 'TSLA', 'MSFT'][:7]
gics_sectors = ['Technology', 'Technology', 'Consumer Discretionary', 'Communication Services', 'Communication Services', 'Consumer Discretionary', 'Technology'][:7]
gics_sub_industries = ['Electronic Equipment, Instruments & Components', 'Internet Services & Products', 'Internet & Direct Marketing Retail', 'Interactive Media & Services', 'Movies & Entertainment', 'Internet & Direct Marketing Retail', 'Systems Software'][:7]
adj_closes = np.random.randint(100, 1000, size=7)
return_values = np.random.rand(7)
layoff_news = np.random.randint(2, size=7)
num_company_layoff_news = np.random.randint(10, 50, size=7)
num_sub_industry_layoff_news = np.random.randint(5, 20, size=7)
num_sector_layoff_news = np.random.randint(20, 100, size=7)

# Create the dataframe
data = {'Date': dates,
        'Symbol': symbols,
        'GICS sector': gics_sectors,
        'GICS sub-industry': gics_sub_industries,
        'Adj.Close': adj_closes,
        'Return Value': return_values,
        'layoff news(1/0)': layoff_news,
        'number of company layoff news': num_company_layoff_news,
        'number of GICS sub-industry layoff news': num_sub_industry_layoff_news,
        'number of GICS Sector layoff news': num_sector_layoff_news}

df = pd.DataFrame(data)

In [6]:
df

,Date,Symbol,GICS sector,GICS sub-industry,Adj.Close,Return Value,layoff news(1/0),number of company layoff news,number of GICS sub-industry layoff news,number of GICS Sector layoff news
0,2022-01-01,AAPL,Technology,"Electronic Equipment, Instruments & Components",205,0.157500,0,43,15,52
1,2022-01-02,GOOG,Technology,Internet Services & Products,307,0.574443,1,12,16,51
2,2022-01-03,AMZN,Consumer Discretionary,Internet & Direct Marketing Retail,491,0.854266,1,31,12,22
3,2022-01-04,FB,Communication Services,Interactive Media & Services,906,0.639146,1,32,5,62
4,2022-01-05,NFLX,Communication Services,Movies & Entertainment,795,0.508471,1,15,9,67
5,2022-01-06,TSLA,Consumer Discretionary,Internet & Direct Marketing Retail,759,0.354832,0,30,16,60
6,2022-01-07,MSFT,Technology,Systems Software,877,0.468089,0,30,5,80

In [9]:
import pandas as pd
import numpy as np

# Create some fake data
dates = pd.date_range('20220101', periods=7)
symbols = ['AAPL', 'GOOG', 'AMZN', 'FB', 'NFLX', 'TSLA', 'MSFT'][:7]
gics_sectors = ['Technology', 'Technology', 'Consumer Discretionary', 'Communication Services', 'Communication Services', 'Consumer Discretionary', 'Technology'][:7]
gics_sub_industries = ['Electronic Equipment, Instruments & Components', 'Internet Services & Products', 'Internet & Direct Marketing Retail', 'Interactive Media & Services', 'Movies & Entertainment', 'Internet & Direct Marketing Retail', 'Systems Software'][:7]
adj_closes = np.random.randint(100, 1000, size=7)
return_values = np.random.rand(7)
layoff_news = np.random.randint(2, size=7)
num_company_layoff_news = np.random.randint(10, 50, size=7)
num_sub_industry_layoff_news = np.random.randint(5, 20, size=7)
num_sector_layoff_news = np.random.randint(20, 100, size=7)

# Create the dataframe
data = {'Date': dates,
        'Symbol': symbols,
        'GICS sector': gics_sectors,
        'GICS sub-industry': gics_sub_industries,
        'Adj.Close': adj_closes,
        'Return Value': return_values,
        'layoff news(1/0)': layoff_news,
        'number of company layoff news': num_company_layoff_news,
        'number of GICS sub-industry layoff news': num_sub_industry_layoff_news,
        'number of GICS Sector layoff news': num_sector_layoff_news}

df = pd.DataFrame(data)

# Group the dataframe by GICS sub-industry and assign the same value for num_sub_industry_layoff_news for each group
df['number of GICS Sector layoff news'] = df.groupby('GICS sector')['number of GICS Sector layoff news'].transform('first')

In [10]:
df

,Date,Symbol,GICS sector,GICS sub-industry,Adj.Close,Return Value,layoff news(1/0),number of company layoff news,number of GICS sub-industry layoff news,number of GICS Sector layoff news
0,2022-01-01,AAPL,Technology,"Electronic Equipment, Instruments & Components",788,0.469632,1,31,14,84
1,2022-01-02,GOOG,Technology,Internet Services & Products,212,0.211749,0,40,13,84
2,2022-01-03,AMZN,Consumer Discretionary,Internet & Direct Marketing Retail,616,0.234363,1,18,7,44
3,2022-01-04,FB,Communication Services,Interactive Media & Services,859,0.012650,1,42,16,95
4,2022-01-05,NFLX,Communication Services,Movies & Entertainment,191,0.843123,1,16,14,95
5,2022-01-06,TSLA,Consumer Discretionary,Internet & Direct Marketing Retail,627,0.156233,1,24,18,44
6,2022-01-07,MSFT,Technology,Systems Software,705,0.406136,0,44,12,84

In [19]:
import pandas as pd
import numpy as np

# Create some fake data
dates = pd.date_range('20220101', periods=7)
symbols = ['AAPL', 'GOOG', 'AMZN', 'FB', 'NFLX', 'TSLA', 'MSFT'][:7]
gics_sectors = ['Technology', 'Technology', 'Consumer Discretionary', 'Communication Services', 'Communication Services', 'Consumer Discretionary', 'Technology'][:7]
gics_sub_industries = ['Internet Services & Products', 'Internet Services & Products', 'Internet & Direct Marketing Retail', 'Interactive Media & Services', 'Movies & Entertainment', 'Internet & Direct Marketing Retail', 'Systems Software'][:7]
adj_closes = np.random.randint(100, 1000, size=7)
return_values = np.random.rand(7)
layoff_news = np.random.randint(2, size=7)
num_company_layoff_news = np.random.randint(10, 50, size=7)

# Set num_company_layoff_news to 0 if layoff_news is 0
num_company_layoff_news[layoff_news == 0] = 0

# Create the dataframe
data = {'Date': dates,
        'Symbol': symbols,
        'GICS sector': gics_sectors,
        'GICS sub-industry': gics_sub_industries,
        'Adj.Close': adj_closes,
        'Return Value': return_values,
        'layoff news(1/0)': layoff_news,
        'number of company layoff news': num_company_layoff_news}

df = pd.DataFrame(data)

# Group the dataframe by GICS sub-industry and assign the sum of num_sub_industry_layoff_news for each group
df['number of GICS sub-industry layoff news'] = df.groupby('GICS sub-industry')['number of company layoff news'].transform('sum')
df['number of GICS Sector layoff news'] = df.groupby('GICS sector')['number of company layoff news'].transform('sum')

df

,Date,Symbol,GICS sector,GICS sub-industry,Adj.Close,Return Value,layoff news(1/0),number of company layoff news,number of GICS sub-industry layoff news,number of GICS Sector layoff news
0,2022-01-01,AAPL,Technology,Internet Services & Products,243,0.456637,1,49,67,67
1,2022-01-02,GOOG,Technology,Internet Services & Products,458,0.815360,1,18,67,67
2,2022-01-03,AMZN,Consumer Discretionary,Internet & Direct Marketing Retail,128,0.291550,0,0,42,42
3,2022-01-04,FB,Communication Services,Interactive Media & Services,765,0.414708,0,0,0,36
4,2022-01-05,NFLX,Communication Services,Movies & Entertainment,876,0.362927,1,36,36,36
5,2022-01-06,TSLA,Consumer Discretionary,Internet & Direct Marketing Retail,693,0.636206,1,42,42,42
6,2022-01-07,MSFT,Technology,Systems Software,193,0.780105,0,0,0,67

In [15]:
df=pd.DataFrame()
df

Empty DataFrame
Columns: []
Index: []